[SDR] Artist Scraper
maxoja/jampify-core pull request #49
Opened 2023-09-27 21:01 UTC by ChungWasawat

Resolve #7 

- add function to connect to spotify/pocketbase, scrape data, and write data to database in `artist_scraping.py `
- using Prefect to automate artist-scraping process in `artist_pipeline.py`
- other files are created as the instructions provided in readme.md

2023-09-28 19:19 UTC, maxoja requested changes

2023-09-28 19:19 UTC, maxoja commented on data-scraper/artist_scraping.py
> +def get_artists_list(spotipy: spotipy.Spotify, year: int):
can you also put your popularity filter into this function as well
and rename `popularity` to `minimum_popularity`

2023-09-28 19:19 UTC, maxoja commented on data-scraper/artist_scraping.py
> +                                        crawled_related_artists, crawled_albums, manual_notes])
please extract this method
`convert_spotify_artist_to_pb_row(spotify_artist_object: dict) -> dict`

we can basically do this from this point
![image](https://github.com/maxoja/jampify-core/assets/11785512/6b88bab7-d3e0-4124-a0f2-4dc849ec77e8)

2023-09-28 19:19 UTC, maxoja commented on data-scraper/artist_scraping.py
> +    while offset+limit <= 1000:
you can use next URL from the returned object from spotify. This can make this while loop simpler
https://developer.spotify.com/documentation/web-api/reference/search
![Uploading image.png…]()

2023-09-28 19:19 UTC, maxoja commented on data-scraper/artist_scraping.py
> +        print(e)
We should keep this but in another place. It can be moved to reference.py for example

2023-09-28 19:19 UTC, maxoja commented on data-scraper/artist_scraping.py
> +from pocketbase.utils import ClientResponseError
these are new dependencies, please add them to project's requirements.txt

2023-09-28 19:19 UTC, maxoja commented on data-scraper/artist_scraping.py
> +                if artist['popularity'] >= popularity:
it would help to make code less nested and more readable if instead of
```
for _ in []:
    if condition:,
        # do things
        # do things
        # do things
        # do things
        # do things
```
use this structure
```
for _ in []:
    if not condition:
        break
    # do things
    # do things
    # do things
    # do things
    # do things
```

2023-09-28 19:19 UTC, maxoja commented on data-scraper/artist_scraping.py
> +def get_artists_list(spotipy: spotipy.Spotify, year: int):
and rename function to `search_artists_as_rows() -> list[dict]`

2023-09-28 19:20 UTC, maxoja commented on data-scraper/artist_scraping.py
> +    while offset+limit <= 1000:
![image](https://github.com/maxoja/jampify-core/assets/11785512/19e4d735-db57-464a-93f5-b86d8dd39dae)

2023-09-29 15:39 UTC, ChungWasawat commented on data-scraper/artist_scraping.py
> +from pocketbase.utils import ClientResponseError
You mean requirements-win.txt and requirements-mac-silicon.txt, right?

2023-09-29 16:48 UTC, maxoja commented on data-scraper/artist_scraping.py
> +from pocketbase.utils import ClientResponseError
Yupp that's right

2023-09-29 19:12 UTC, maxoja commented
I merged main into this and resolved the conflicts in .gitignore file

2023-09-29 21:15 UTC, maxoja approved these changes
Happy to merge after one last fix - thanks!

2023-09-29 21:15 UTC, maxoja commented on data-scraper/artist_scraping.py
> +            raise error
In my other project in TypeScript, we use this to check for duplication. Basically if getList return empty -> there's no duplicate. I think it's a safer way to check because then we can catch actual error from another kind of Exception
![image](https://github.com/maxoja/jampify-core/assets/11785512/bc3ba598-1d69-45fd-a537-8fec3ba845e8)

2023-09-30 10:42 UTC, merged

2023-09-30 14:13 UTC, maxoja commented
Sorry I should have mentioned this before, but can you make the check function check length == 0 within and return True/False? It will make it easier for use by caller.

2023-09-30 18:52 UTC, ChungWasawat commented
> Sorry I should have mentioned this before, but can you make the check function check length == 0 within and return True/False? It will make it easier for use by caller.

Do I need to create a new PR?

2023-09-30 18:54 UTC, maxoja commented
Yeah you can create new PR